### ISSUE TITLE
Feature: :where option for t method that scopes translation

### ISSUE THREAD

**Issue by lancecarlson** [svenfuchs/i18n-active_record#103]
It would be very cool if you could add another column to the translations table like `account_id` or something and be able to scope translations down with something like I18n.t('welcome_message', where: {account_id: account_id}). It would broaden the use cases for this gem quite a bit as I have to implement this custom feature myself right now for our uses cases.

If you think it would be a good idea, I could work on a PR for it. I understand it doesn't conform to the higher level rails API, but there are advantages to querying your database directly over using YML. Why not leverage them?

**Comment by timsly** [comment]
Thanks for your suggestion @lancecarlson 
This feature looks like very specific to your project
I understand that you want to make sure only some specific keys are involved in the lookup but this can be achieved by extending `I18n::Backend::ActiveRecord::Translation` and adding your logic on top

**Comment by lancecarlson** [comment]
@timsly certainly "account_id" is very specific to my project, but the interface I'm describing can be used pretty generically. Having the notion of a where clause could apply to all kinds of use cases.

**Comment by timsly** [comment]
I agree with you, having this addition would be great but I am not sure `i18n-active_record` is the right place to add it.
`i18n-active_record` basically an `i18n` backend(storage) so what it does is just implements the interface defined in `i18n`. 
From my point of view adding new features from a backend doesn't look correct so I can see this more as an `i18n` plugin rather than `i18n-active_record` addition.

**Comment by timfjord** [comment]
I am closing this one as I don't think it will be implemented.
