### ISSUE TITLE
path for form helper

### ISSUE THREAD

**Issue by D4v1dW3bb** [svenfuchs/i18n-active_record#105]
When making a form i got an error:

`ActionView::Template::Error (undefined method 'i18n_backend_active_record_translation_path' for #<#<Class:0x00007f04a9399298>:0x00007f04917462c8>):`
when adding `url: translations_path` to the form it worked again.
I think this originates from the initializer line:
`Translation = I18n::Backend::ActiveRecord::Translation`
There for `Translation.name` and `Translation.sti_name` is `I18n::Backend::ActiveRecord::Translation'

So when you call a form without an url parameter `i18n_backend_active_record_translation_path`  is automatically generated for url.

Would be nice to ad a comment in the readme to put ` add  "url: <translation_view_dir>_path" to form_with`

**Comment by timsly** [comment]
In general, that fact that the `i18n_backend_active_record_translation_path` is not defined but the `translations_path` is has nothing to do with the initializer.
`translations_path` works only because you have an entry in `routes.rb` that defines a route named `translations`, so if you add something like
```ruby
get '/something' => 'my_controller#my_action', as: :i18n_backend_active_record_translation
```
most likely it will work without `url: translations_path`

You can also try
```ruby
class Translation < I18n::Backend::ActiveRecord::Translation
end
```
Adding the note about the path helper might be confusing because this gem doesn't really add routes and controllers and acts purely as a backend for `I18n` gem.

**Comment by D4v1dW3bb** [comment]
I changed

 

`Translation = I18n::Backend::ActiveRecord::Translation`

 

In the initializer to:

 

```
class Translation < I18n::Backend::ActiveRecord::Translation
end
```
 
An now it works as expected.
 
I think it’s wise to change this in the default `I18n_active_record.erb`
 
Regards,
 
Didier

**Comment by timsly** [comment]
It is not recomennded to keep `class Translation < I18n::Backend::ActiveRecord::Translation` in the initializer, it should be in `app/models/translation.rb`
Basically this way we define our own AR model but inherit from the model from the gem.
I shared that just to illustrate that the issue wasn't really related to the initializer.

It is expected that `I18n::Backend::ActiveRecord::Translation` returns `i18n_backend_active_record_translation_path`.
Usage of the model in helpers like `form_for` or `link_to` is not supported because this gem doesn't provide any controllers,  routes to handle that.

**Comment by D4v1dW3bb** [comment]
> It is expected that I18n::Backend::ActiveRecord::Translation returns i18n_backend_active_record_translation_path.
> Usage of the model in helpers like form_for or link_to is not supported because this gem doesn't provide any controllers, routes to handle that.

The gem does not provide it but it's expected the users of the gem are going to use it. Their not going to fill the translation table by hand.  so they will need to make controllers, views and routes. Therefor the translation table should act like every other model whether it's installed by a gem or the programmer implements it himself.

**Comment by timsly** [comment]
You can use `i18n_backend_active_record_translation` name in your routes because this is what the model generates. 

But I am going to revisit `Translation = I18n::Backend::ActiveRecord::Translation` part in the initializer and probably include `class Translation < I18n::Backend::ActiveRecord::Translation` model instead.

**Comment by floydj** [comment]
> You can use `i18n_backend_active_record_translation` name in your routes because this is what the model generates.

So how exactly is this done?

**Comment by timfjord** [comment]
> > You can use `i18n_backend_active_record_translation` name in your routes because this is what the model generates.
> 
> So how exactly is this done?

The easiest way is to have something like this in the `routes.rb`:
```ruby
post '/some_path', to: 'my_controller#my_action', as: 'i18n_backend_active_record_translation'
```
But we have recently added support [for custom models](https://github.com/svenfuchs/i18n-active_record?tab=readme-ov-file#custom-translation-model) so it now should be possible to use our own model (please note that there might be some issues with the latest version of rails with referencing a model from the initialisers)
