### ISSUE TITLE
Using I18nAR in isolation

### ISSUE THREAD

**Issue by nitsujri** [svenfuchs/i18n-active_record#89]
Hi guys, thanks for this amazing gem!

I was hoping to use this in an isolated portion of my site.

```
# initializers/i18n_active_record.rb
require 'i18n/backend/active_record'

I18nAR = I18n.clone
I18nAR.backend = I18n::Backend::ActiveRecord.new
```
The hope was with the above code I could do something like `I18nAR.t("meow")` in my views then it would explicitly use the database to pull the translation.

Problem is I was trying to duplicate the `I18n` singleton, but when I set the backend of the cloned, `I18nAR` it affects I18n and changes it to using this gem.

Any help would be much appreciated. Thanks!

**Comment by timsly** [comment]
It is because `I18n` uses `Thread.current` to store config(`.backend`, etc) - https://github.com/svenfuchs/i18n/blob/master/lib/i18n.rb#L26
So most like you need to change that, for example, with the following code
```ruby
I18nAR = I18n.clone
def I18nAR.config
  Thread.current[:i18n_ar_config] ||= I18n::Config.new
end
I18nAR.backend = I18n::Backend::ActiveRecord.new
```
There might be some other places that need to be fixed in the same manner, because `I18n` wasn't designed with such feature in mind

**Comment by nitsujri** [comment]
@timsly thanks so much. This is enough to get me in the right direction.
